sudo: required
dist: xenial
language: scala

# https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  # using jabba for custom jdk management
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.1/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@1.8-0
  - jabba install adopt@1.11-0
  - jabba install adopt@1.14.0-0

jobs:
  include:
    - stage: "Test-adopt@1.8-0"
      name: "Test FlixDb on adopt@1.8-0"
      script:
        - jabba use "adopt@1.8-0"
        - sbt +test

