{
 "title": "HikariCP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "poolname", "label": "Pool Name", "query": "label_values(pool)" },
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_active_connections{instance=~\"$instance\", pool=~\"$poolname\"}",
     "legendFormat": "Active Connections: $poolname $instance"
    }
   ]
  },
  {
   "title": "Configuration - Maximum Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_max_connections{instance=~\"$instance\", pool=~\"$poolname\"})"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_idle_connections{instance=~\"$instance\", pool=~\"$poolname\"}",
     "legendFormat": "Idle Connections: $poolname $instance"
    }
   ]
  },
  {
   "title": "Configuration - Minimum Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_min_connections{instance=~\"$instance\", pool=~\"$poolname\"})"
    }
   ]
  }
 ]
}