{
 "title": "Change Data Capture",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Inserts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of inserts" }
   ],
   "targets": [
    { "expr": "rate(inserts_total[1m])", "legendFormat": "SQL Inserts Captured" }
   ]
  },
  {
   "title": "Deletes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of deletes" }
   ],
   "targets": [
    { "expr": "rate(deletes_total[1m])", "legendFormat": "SQL Deletes Captured" }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of updates" }
   ],
   "targets": [
    { "expr": "rate(updates_total[1m])", "legendFormat": "SQL Updates Captured" }
   ]
  }
 ]
}